### ISSUE TITLE
Change to default doesn't propagate to other journals

### ISSUE THREAD

**Issue by arcanistzed** [League-of-Foundry-Developers/document-sheet-registrar#6]
If you change the default sheet using the header button, it updates for the current journal. If I open a new sheet, it still uses the old default, even if it says the right thing in the config

**Comment by arcanistzed** [comment]
https://user-images.githubusercontent.com/82790112/130167816-fadf91d9-1a84-47c9-932a-3e8492e58ce6.mp4

**Comment by zeel01** [comment]
This seems to be caused by an issue with Foundry Core, its effects on this library are only due to copying the `EntitySheetConfig.updateDefaultSheets` which contains the bug/omission.
